export const phrases_for_thinking = [
    "What patterns emerge from these cards?",
    "How does this resonate with my current situation?",
    "What fears might these cards be highlighting?",
    "What opportunities am I overlooking?",
    "How can I align my actions with this guidance?",
    "What part of myself needs more attention?",
    "How might my perspective be limiting me?",
    "What truth am I avoiding?",
    "Where can I find balance in this situation?",
    "What lesson is being presented to me?",
    "How can I embrace change more fully?",
    "What strengths do I possess to overcome challenges?",
    "What does my intuition say about these cards?",
    "How can I cultivate more self-compassion?",
    "What old beliefs need to be released?",
    "How can I better support myself?",
    "What new path is opening up for me?",
    "What is the universe trying to tell me?",
    "How can I be more present in my daily life?",
    "What relationships need nurturing?",
    "Where am I resisting growth?",
    "How can I tap into my inner wisdom?",
    "What boundaries need to be set or reinforced?",
    "How can I honor my authentic self?",
    "What shadows need to be brought to light?",
    "How can I cultivate more gratitude?",
    "What steps can I take towards my goals?",
    "How can I be more compassionate towards others?",
    "What habits are no longer serving me?",
    "How can I embrace uncertainty?",
    "What aspects of myself am I neglecting?",
    "How can I create more balance in my life?",
    "What new perspective can I adopt?",
    "How can I better align with my values?",
    "What hidden potential am I not utilizing?",
    "How can I be more open to receiving?",
    "What past experiences are influencing my present?",
    "How can I cultivate more inner peace?",
    "What emotions need to be acknowledged and processed?",
    "How can I be more gentle with myself?",
    "What sources of joy am I overlooking?",
    "How can I better express my authentic self?",
    "What limiting beliefs are holding me back?",
    "How can I embrace my personal power?",
    "What area of my life needs more attention?",
    "How can I be more mindful in my decisions?",
    "What unconscious patterns are at play?",
    "How can I cultivate more self-trust?",
    "What new skills or knowledge do I need to acquire?",
    "How can I create more meaningful connections?"
]

export const fortune_cookie_phrases = [
    "A new path will reveal itself soon.",
    "Your intuition is your greatest guide.",
    "Embrace change, for it brings opportunity.",
    "The answers you seek are within you.",
    "A small act of kindness will return to you tenfold.",
    "Your creativity will lead you to success.",
    "Trust in the journey, even when you cannot see the destination.",
    "An unexpected ally will appear in your life.",
    "Your perseverance will be rewarded.",
    "A door closes, but a window opens.",
    "Your inner strength is your greatest asset.",
    "A period of personal growth is on the horizon.",
    "Listen to your heart, it whispers the truth.",
    "Your unique perspective will solve a long-standing problem.",
    "A pleasant surprise awaits you.",
    "Your past holds the key to your future.",
    "Patience now will lead to joy later.",
    "An old friend will bring new wisdom.",
    "Your courage will be tested, but not found wanting.",
    "A dream deferred will soon become reality.",
    "Your generosity will return to you in unexpected ways.",
    "A new chapter in your life is about to begin.",
    "Your true self is ready to emerge.",
    "An important lesson will present itself soon.",
    "Your kindness will light the way for others.",
    "A long-held wish will soon be granted.",
    "Your resilience will see you through tough times.",
    "An opportunity for growth is disguised as a challenge.",
    "Your words have the power to change lives.",
    "A moment of clarity will guide your next steps.",
    "Your compassion will heal old wounds.",
    "An unexpected journey will lead to self-discovery.",
    "Your patience will soon be rewarded.",
    "A new perspective will bring unexpected joy.",
    "Your authenticity will attract genuine connections.",
    "An old problem will find a new solution.",
    "Your inner wisdom holds the answers you seek.",
    "A small change will lead to big results.",
    "Your positive attitude will open many doors.",
    "An act of forgiveness will set you free.",
    "Your creativity will solve an impossible puzzle.",
    "A period of reflection will lead to great insights.",
    "Your determination will overcome all obstacles.",
    "An unexpected turn of events will work in your favor.",
    "Your empathy will bridge divides.",
    "A long-forgotten talent will resurface.",
    "Your patience will be tested, but rewarded.",
    "An important truth will be revealed.",
    "Your integrity will be your guiding light.",
    "A new adventure is just around the corner."
]